name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: abatilo/actions-poetry@v3
      - run: poetry install --no-interaction --no-root
      - run: poetry run python -c "import telethon, weasyprint, openai, jinja2; print('✓ imports ok')" 